name: Build, test, and publish Docker Image

env:
  {%- raw %}
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  {%- endraw %}

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  schedule:
    # Weekly, at 07:00 on Monday UTC time
    - cron: "0 7 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  {%- raw %}
  group: ${{ github.workflow }}-${{ github.ref }}
  {%- endraw %}
  cancel-in-progress: true

jobs:
  build-test-publish-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v6

      - name: Set Up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Dev Dependencies 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

      - name: Get commit sha, this will be used as a tag later on 🏷
        shell: bash
        run: |
          echo "sha12=$(echo ${GITHUB_SHA} | cut -c1-12)" >> $GITHUB_OUTPUT
        id: get_sha

      - name: Build image 🛠
        {%- raw %}
        run: >
          docker build
          --rm --force-rm
          --tag ${{ env.OWNER }}/${{ env.IMAGE_NAME }}
          --tag ${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{steps.get_sha.outputs.sha12}}
          image/
        {%- endraw %}
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Run tests ✅
        run: python3 -m pytest tests
        env:
          TEST_IMAGE: "{{cookiecutter.stack_org}}/{{cookiecutter.stack_name}}"

      - name: Login to Docker Hub 🔐
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
        {%- raw %}
          username: ${{ env.OWNER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        {%- endraw %}

      - name: Push Image to Docker Hub 📤
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        {%- raw %}
        run: docker push --all-tags ${{ env.OWNER }}/${{ env.IMAGE_NAME }}
        {%- endraw %}
