name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  run-hooks:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit

      - name: Run pre-commit hooks
        run: make pre-commit-all
